# Generated by Django 3.2.8 on 2021-10-10 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('idPlan', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reserva')),
            ],
        ),
    ]
