# Generated by Django 3.2.8 on 2021-10-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reserva')),
            ],
        ),
    ]
