# Generated by Django 3.2.8 on 2021-10-10 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('precioDia', models.IntegerField()),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reserva')),
            ],
        ),
    ]
