# Generated by Django 3.2.8 on 2021-10-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
