# Generated by Django 3.2.8 on 2021-10-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_documneto_cliente_documento_persona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='descripcion',
            new_name='tipoPlan',
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
